version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  sass:
    build: 
      context: .
      dockerfile: Dockersass
    command: sass --poll --watch ./sass/style.scss:./style.css
    volumes:
      - ./wp-content/themes/because-shes-cross-all-of-the-time:/app
